Support database API
milvus-io/pymilvus pull request #1401
Opened 2023-04-27 06:31 UTC by jaime0815

/kind improvement

2023-04-27 06:37 UTC, XuanYang-cn requested changes

2023-04-27 08:40 UTC, longjiquan requested changes

2023-04-27 08:40 UTC, longjiquan commented on pymilvus/grpc_gen/milvus_pb2.py
> +from . from . from . from . import common_pb2 as common__pb2
Use `make gen_proto` to update the generated py files.

2023-04-27 08:40 UTC, longjiquan commented on pymilvus/grpc_gen/schema_pb2.py
> +from . from . from . from . import common_pb2 as common__pb2
Use `make gen_proto` to update the generated py files.

2023-04-27 08:40 UTC, longjiquan commented on pymilvus/grpc_gen/schema_pb2.pyi
> +from . from . from . from . import common_pb2 as _common_pb2
Use `make gen_proto` to update the generated py files.

2023-04-27 08:40 UTC, longjiquan commented on pymilvus/__init__.py
> +    'utility', 'db', 'DefaultConfig', 'ExceptionsMessage', 'MilvusUnavailableException', 'BulkInsertState',
why not export these three apis? `db` here seems strange.

2023-04-27 08:43 UTC, longjiquan commented
Please also add this feature to master branch.

2023-04-29 06:59 UTC, czs007 commented on pymilvus/orm/connections.py
> +    def connect(self, alias=Config.MILVUS_CONN_ALIAS, user="", password="", db_name="default", **kwargs):
It is recommended to fill in empty "or None here, and convert it to default at the server.

2023-05-05 03:28 UTC, longjiquan requested changes

2023-05-05 03:28 UTC, longjiquan commented on pymilvus/client/grpc_handler.py
> +        status = self._stub.CreateDatabase.future(request, timeout=timeout).result()
Do not use `future`.

2023-05-05 03:28 UTC, longjiquan commented on pymilvus/client/grpc_handler.py
> +        status = self._stub.DropDatabase.future(request, timeout=timeout).result()
Do not use `future`.

2023-05-05 03:28 UTC, longjiquan commented on pymilvus/client/grpc_handler.py
> +        response = self._stub.ListDatabases.future(request, timeout=timeout).result()
Do not use `future`.

2023-05-05 03:44 UTC, longjiquan approved these changes
/lgtm

2023-05-05 03:44 UTC, merged

2023-05-05 03:48 UTC, longjiquan commented
Please also add this feature into master branch.