Support partition key
milvus-io/pymilvus pull request #1425
Opened 2023-05-11 08:57 UTC by xige-16

2023-05-11 09:35 UTC, XuanYang-cn requested changes

2023-05-11 09:35 UTC, XuanYang-cn commented on pymilvus/client/abstract.py
> +            "partitions": self.partitions,
please change "partitions" into "num_partitions"

2023-05-11 13:01 UTC, longjiquan requested changes

2023-05-11 13:04 UTC, longjiquan commented
/approve
/lgtm

2023-05-11 13:04 UTC, longjiquan commented
Please remember to cherry-pick this feature to master branch. @xige-16

2023-05-11 13:05 UTC, merged

2023-05-25 07:27 UTC, xige-16 commented
https://github.com/milvus-io/pymilvus/issues/1458