feat(pymilvus/settings.py): Load configuration without altering the environment
milvus-io/pymilvus pull request #2192
Opened 2024-07-22 13:47 UTC by laipz8200

related #2166.

This PR will replace `environs` with the more lightweight `python-dotenv`. It can load configuration from the dot env file without altering the system environment.

2024-07-23 20:01 UTC, laipz8200 commented
/assign @longjiquan

2024-07-25 03:11 UTC, XuanYang-cn requested changes
Please replace the dependencies in pyproject.toml too.

2024-07-29 02:59 UTC, XuanYang-cn commented
/lgtm
/approve

2024-08-06 08:50 UTC, XuanYang-cn approved these changes

2024-08-15 08:09 UTC, laipz8200 commented
Hello @XuanYang-cn, will this be merged? What should I do?

2024-08-17 01:17 UTC, laipz8200 commented on pymilvus/settings.py
> +env_dict = dotenv_values(".env")
Thank you for your suggestion. I previously misunderstood the behavior of `load_dotenv`, but I will use it now.

2024-08-17 03:16 UTC, laipz8200 commented on pyproject.toml
> +    "python-dotenv==1.0.1",
Sorry about that. I changed it to `>=1.0.1, <2.0.0`

2024-10-08 09:38 UTC, XuanYang-cn commented
Sorry about the late response!
/lgtm
/approve

2024-10-08 09:39 UTC, merged

2024-10-08 09:40 UTC, laipz8200 commented
@XuanYang-cn Thank you:)

2025-01-13 20:15 UTC, sloria commented
fwiw, `python-dotenv`'s `load_env` _does_ alter `os.environ`. in fact, `environs` [delegates to `load_env`](https://github.com/sloria/environs/blob/88d9df372ad933d2b90e2e29461911b74fae8d1b/src/environs/__init__.py#L414-L421), so this PR doesn't really change that.

i'm planning to add support for reading `.env` without altering `os.environ` https://github.com/sloria/environs/issues/393 .

btw this isn't to argue againt this PR getting merged--i'm all for removing dependencies when sensible, even if they're my libraries 😅 . just raising that this PR may not have achieved its original intent