[Issue763_Bug] Add a English version of contributing_cn.md
milvus-io/pymilvus pull request #849
Opened 2021-12-23 07:19 UTC by DingQK

This PR:
- translate contributing_cn.md into English
- check the grammar using grammarly

2021-12-23 09:55 UTC, XuanYang-cn commented
/assign @LocoRichard

2021-12-23 10:21 UTC, LocoRichard commented
Hi @DingQK , thank you so much for your interest in contributing to PyMilvus Project. I have reviewed your translation. Unfortunately, I found it failed to meet our criteria for documentation. We cannot accept unedited machine translation. However, we really appreciate your effort. Stay tuned if you are still interested in contributing to this project.

2021-12-23 10:26 UTC, DingQK commented
> Hi @DingQK , thank you so much for your interest in contributing to PyMilvus Project. I have reviewed your translation. Unfortunately, I found it failed to meet our criteria for documentation. We cannot accept unedited machine translation. However, we really appreciate your effort. Stay tuned if you are still interested in contributing to this project.

Hi! This is not a machine translation. I translate it myself and check grammar mistakes with grammarly (an app for grammar mistakes checking).

2021-12-23 10:27 UTC, DingQK commented
> Hi @DingQK , thank you so much for your interest in contributing to PyMilvus Project. I have reviewed your translation. Unfortunately, I found it failed to meet our criteria for documentation. We cannot accept unedited machine translation. However, we really appreciate your effort. Stay tuned if you are still interested in contributing to this project.

Hi @LocoRichard ! This is not a machine translation. I translate it myself and check grammar mistakes with grammarly (an app for grammar mistakes checking). If the content is wrong, I can change the content according to your need. Thank you!

2021-12-23 10:43 UTC, LocoRichard commented
> > Hi @DingQK , thank you so much for your interest in contributing to PyMilvus Project. I have reviewed your translation. Unfortunately, I found it failed to meet our criteria for documentation. We cannot accept unedited machine translation. However, we really appreciate your effort. Stay tuned if you are still interested in contributing to this project.
> 
> Hi @LocoRichard ! This is not a machine translation. I translate it myself and check grammar mistakes with grammarly (an app for grammar mistakes checking). If the content is wrong, I can change the content according to your need. Thank you!

I am sorry for the misunderstanding. The content is so far correct. The only problem is that some of the translation does not conform to the style of English writing.
If that is the case, would you mind polishing the language together with me? It will take a bit longer for me to comment and you to make changes accordingly.

2021-12-23 10:46 UTC, DingQK commented
> > > Hi @DingQK , thank you so much for your interest in contributing to PyMilvus Project. I have reviewed your translation. Unfortunately, I found it failed to meet our criteria for documentation. We cannot accept unedited machine translation. However, we really appreciate your effort. Stay tuned if you are still interested in contributing to this project.
> > 
> > 
> > Hi @LocoRichard ! This is not a machine translation. I translate it myself and check grammar mistakes with grammarly (an app for grammar mistakes checking). If the content is wrong, I can change the content according to your need. Thank you!
> 
> I am sorry for the misunderstanding. The content is so far correct. The only problem is that some of the translation does not conform to the style of English writing. If that is the case, would you mind polishing the language together with me? It will take a bit longer for me to comment and you to make changes accordingly.

Yes! I can revise according to your need, and I believe I can learn a lot in the process. Thank you so much！

2021-12-23 10:52 UTC, LocoRichard commented
> 

Brilliant! I will let you know when I finish reviewing and commenting.

2021-12-23 11:08 UTC, DingQK commented
> Brilliant! I will let you know when I finish reviewing and commenting. And a huge THANK for your interest and patience.

Ok!

2021-12-28 09:25 UTC, LocoRichard commented
> > Brilliant! I will let you know when I finish reviewing and commenting. And a huge THANK for your interest and patience.
> 
> Ok!

HI, I have gone through the doc and made some comments, please check and give me some feedback if necessary.

2021-12-28 09:26 UTC, LocoRichard requested changes

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +`docs/`: Contains source codes for documentation except for API Reference and uses sphinx to create documentation. Most documentation are in folder `rst` under `docs/source`.
`docs/`: Contains source documentation (except for API Reference) that created by sphinx; most documentation are stored as `.rst` files under `docs/source`.

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +`examples/`: Contains python scripts, which can be run directly, to introduce the usage of PyMiluvs API through examples.
"Python"

Use upper case whenever needed.

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +`pymilvus/`：PyMilvus source codes.
Contains

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +`tests/`: Unit Test.
Contains

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +`OWNERS`: This file designates reviewers and approvers for the current directory. They are chosen according to their activity and code contribution. Active contributors are listed as reviewers, under
`OWNERS`: This file designates reviewers and approvers for the current directory. They are chosen according to their participation and code contribution. Active contributors are listed as reviewers, responsible for code reviews. Reviewers who have been active and reviewing codes for a period of time are listed as approvers. They are in charge of reviewing content apart from codes. If you submit a PR and do not know who can help you review the code, you can assign reviewers and approvers from this file to review your PR.

2021-12-28 09:26 UTC, LocoRichard commented on CONTRIBUTING.md
> +Apart from dealing with codes and machines, you can always communicate with people from the Milvus community. Many new faces join in every day, and if you have encountered the same challenges as they
Apart from dealing with codes and machines, you are always welcome to communicate with any member from the Milvus community. New faces join us every day, and they may as well encounter the same challenges as you faced beore. Feel free to help them. You can pass on the collaborative spirit from the assistance you acquired when you first joined the community. Let us build a collaborative, open-source, exuberant, and tolerant community together!

2021-12-28 10:37 UTC, DingQK commented
Hi @LocoRichard ! Thank you so much for your comments and revisal! I have learned a lot about how to clearly convey ideas in a formal and concise way. Right now, I am wondering do we need to remove all the h2 and h3 without content or we can simply leave them there?

I will revise according to the comments and commit as soon as possible. Thank you so much!

2021-12-29 06:46 UTC, LocoRichard commented
> Hi @LocoRichard ! Thank you so much for your comments and revisal! I have learned a lot about how to clearly convey ideas in a formal and concise way. Right now, I am wondering do we need to remove all the h2 and h3 without content or we can simply leave them there?
> 
> I will revise according to the comments and commit as soon as possible. Thank you so much!

Yes, we'd better delete those titles without content. Please go ahead. Also, please note, in most scenarios, there is only one h1, which is the title of the article at the top.

We sincerely thank you for your contribution, and the patience all the time!

2021-12-29 06:51 UTC, DingQK commented
@LocoRichard  I totally agree. I have deleted the titles and change the titles except the first one into h2 in my latest commit.

2021-12-29 06:53 UTC, LocoRichard commented
/lgtm

2021-12-29 06:53 UTC, LocoRichard approved these changes

2021-12-29 06:53 UTC, LocoRichard commented on CONTRIBUTING.md
> +# What contributions can you make?
This is a h2.

2021-12-29 06:53 UTC, LocoRichard commented on CONTRIBUTING.md
> +# PyMilvus Code Structure
h2 too

2021-12-29 06:53 UTC, LocoRichard commented on CONTRIBUTING.md
> +# Congratulations! You are now the contributor to the Milvus community!
h2

2021-12-29 06:56 UTC, LocoRichard commented
/unassign
/assign @XuanYang-cn

2021-12-29 07:01 UTC, XuanYang-cn commented
/approve

2021-12-29 07:03 UTC, merged