Mep 27: Support Basic Authentication
milvus-io/pymilvus pull request #947
Opened 2022-04-08 03:20 UTC by DragonDriver

Signed-off-by: dragondriver <jiquan.long@zilliz.com>
/kind feature
See also: https://wiki.lfaidata.foundation/display/MIL/MEP+27+--+Support+Basic+Authentication

2022-04-08 03:46 UTC, DragonDriver commented
/hold
Waiting for the related features to be merged in https://github.com/milvus-io/milvus

2022-04-12 02:24 UTC, DragonDriver commented
/unhold

2022-04-12 03:29 UTC, XuanYang-cn requested changes

2022-04-12 03:29 UTC, XuanYang-cn commented on pymilvus/client/grpc_handler.py
> +        self._password = password
Please remove these private information

2022-04-12 03:29 UTC, XuanYang-cn commented on pymilvus/client/grpc_handler.py
> +        self._password = kwargs.get("password", None)
Please remove these private information

2022-04-12 03:29 UTC, XuanYang-cn commented on pymilvus/client/grpc_handler.py
> +        if self._user and self._password:
Private info

2022-04-12 03:29 UTC, XuanYang-cn commented on pymilvus/client/grpc_handler.py
> +        return self._password
Please remove these private information

2022-04-12 03:29 UTC, XuanYang-cn commented on pymilvus/client/grpc_handler.py
> +        self._password = password
Change the credentials in server and change the SDK client

2022-04-12 09:25 UTC, merged